pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'VERSION_PREFIX=$(sed -n ''s/.*<VersionPrefix>\([^<]*\)<\/VersionPrefix>.*/\1/p'' <<< cat ./build/common.props)
      VERSION_SUFFIX=$Build.BuildId
      VERSION="$VERSION_PREFIX.$VERSION_SUFFIX"
      echo "Version: $VERSION"'
  displayName: 'Version'
- script: docker build --target testrunner -t foundatio:test --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
  displayName: 'Build'
- script: docker run --net=host -v $(pwd)/artifacts:/app/artifacts foundatio:test
  displayName: 'Tests'
- script: docker build --target pack -t foundatio:pack --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
  displayName: 'Build Pack'
- script: docker run --rm -v $(pwd)/artifacts:/app/artifacts foundatio:pack
  displayName: 'Pack'
