pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build --target testrunner -t foundatio:test --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
  displayName: 'Build'
  env:
    VERSION_SUFFIX: $(Build.BuildId)-pre
- script: docker run --net=host -v $(pwd)/artifacts:/app/artifacts foundatio:test
  displayName: 'Tests'
- script: docker build --target pack -t foundatio:pack --build-arg VERSION_SUFFIX=${VERSION_SUFFIX} .
  displayName: 'Build Pack'
  env:
    VERSION_SUFFIX: $(Build.BuildId)-pre
- script: docker run --rm -v $(pwd)/artifacts:/app/artifacts foundatio:pack
  displayName: 'Pack'
